
package restogrupo51.views;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import restogrupo51.accesoAdatos.ProductoData;
import restogrupo51.entidades.Producto;

public class ProductosView extends javax.swing.JInternalFrame {
    ProductoData producto = new ProductoData();
    private DefaultTableModel modelo = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    
    public ProductosView() {
        initComponents();
        armarCabecera();
        cargarTabla();
        getContentPane().setBackground(new Color(255,205,110));
        
        // Cambiar el color de fondo de las cabeceras de columna
        JTableHeader header = jtblProductos.getTableHeader();
        header.setDefaultRenderer(new ProductosView.CustomHeaderRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtId = new javax.swing.JTextField();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtPrecio = new javax.swing.JTextField();
        jtxtStock = new javax.swing.JTextField();
        jbtnGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtxtBuscarId = new javax.swing.JTextField();
        jbtnBuscarId = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtxtBuscarCodigo = new javax.swing.JTextField();
        jbtnBuscarPorCodigo = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(785, 500));

        jtblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtblProductosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtblProductos);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productIcon3.png"))); // NOI18N
        jLabel1.setText("Productos");

        jPanel1.setBackground(new java.awt.Color(255, 205, 110));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Formulario Productos");

        jLabel3.setText("ID");

        jLabel4.setText("Codigo");

        jLabel5.setText("Nombre");

        jLabel6.setText("Precio");

        jLabel7.setText("Stock");

        jtxtId.setEditable(false);
        jtxtId.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtxtIdCaretUpdate(evt);
            }
        });

        jbtnGuardar.setBackground(new java.awt.Color(255, 205, 110));
        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        jLabel9.setText("Buscar por ID");

        jtxtBuscarId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBuscarIdMouseClicked(evt);
            }
        });

        jbtnBuscarId.setBackground(new java.awt.Color(255, 205, 110));
        jbtnBuscarId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar16px.png"))); // NOI18N
        jbtnBuscarId.setText("ID");
        jbtnBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarIdActionPerformed(evt);
            }
        });

        jbtnLimpiar.setBackground(new java.awt.Color(255, 205, 110));
        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jbtnModificar.setBackground(new java.awt.Color(255, 205, 110));
        jbtnModificar.setText("Modificar");
        jbtnModificar.setEnabled(false);
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });

        jLabel10.setText("Buscar por Código");

        jtxtBuscarCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBuscarCodigoMouseClicked(evt);
            }
        });

        jbtnBuscarPorCodigo.setBackground(new java.awt.Color(255, 205, 110));
        jbtnBuscarPorCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar16px.png"))); // NOI18N
        jbtnBuscarPorCodigo.setText("Cod");
        jbtnBuscarPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarPorCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(jtxtPrecio)
                                    .addComponent(jtxtStock)
                                    .addComponent(jtxtId)
                                    .addComponent(jtxtCodigo))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnBuscarPorCodigo))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtxtBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnBuscarPorCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jtxtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnGuardar)
                            .addComponent(jbtnModificar)
                            .addComponent(jbtnLimpiar))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnBuscarId)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jbtnEliminar.setBackground(new java.awt.Color(255, 205, 110));
        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.setName(""); // NOI18N
        jbtnEliminar.setOpaque(false);
        jbtnEliminar.setPreferredSize(new java.awt.Dimension(85, 26));
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jbtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jbtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarIdActionPerformed
        
        try {
            Producto producto = new Producto();
            ProductoData productoData = new ProductoData();
            
            producto = productoData.buscarProducto(Integer.parseInt(jtxtBuscarId.getText()));
            if (producto != null) {
                jtxtId.setText(String.valueOf(producto.getIdProducto()));
                jtxtCodigo.setText(producto.getCodigoProducto());
                jtxtNombre.setText(producto.getNombreProducto());
                jtxtPrecio.setText(String.valueOf(producto.getPrecio()));
                jtxtStock.setText(String.valueOf(producto.getStock()));
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe ingresar un número entero");
        }
    }//GEN-LAST:event_jbtnBuscarIdActionPerformed

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        
        try{
            String codigo = jtxtCodigo.getText();
            String nombre = jtxtNombre.getText();
            double precio = Double.parseDouble(jtxtPrecio.getText());
            int stock = Integer.parseInt(jtxtStock.getText());
            
            boolean estado = true;

            Producto producto = new Producto(codigo, nombre, precio, stock, estado);
            ProductoData productoData = new ProductoData();
            
            if (producto != null) {
                productoData.guardarProducto(producto);
            }
            borrarFilas();
            cargarTabla();
            borrarDatos();
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe ingresar un Precio(decimal)/Stock(entero)");
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Debe completar los campos TODOS");
        }
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        ProductoData productoData = new ProductoData();
        
        if (jtblProductos.getSelectedRow() > -1) {
            String idString = jtblProductos.getValueAt(jtblProductos.getSelectedRow(), 0).toString();
            int idProducto = Integer.parseInt(idString);
            Producto prodBuscar = productoData.buscarProducto(idProducto);
            if (prodBuscar.isEstadoProducto())
                productoData.eliminarProducto(prodBuscar.getIdProducto());
            else
                productoData.restaurarProducto(prodBuscar.getIdProducto());
        } else {
            try{
                Producto productoBuscado = productoData.buscarProducto(Integer.parseInt(jtxtId.getText()));
                if (productoBuscado != null) {
                    if (productoBuscado.isEstadoProducto())
                        productoData.eliminarProducto(productoBuscado.getIdProducto());
                    else
                        productoData.restaurarProducto(productoBuscado.getIdProducto());
                }
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Debe ingresar un numero entero en Buscar");
            }
        }
        borrarFilas();
        cargarTabla();
        borrarDatos();
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
        
        try {
            int idProducto = Integer.parseInt(jtxtId.getText());
            String codigo = jtxtCodigo.getText();
            String nombre = jtxtNombre.getText();
            double precio = Double.parseDouble(jtxtPrecio.getText());
            int stock = Integer.parseInt(jtxtStock.getText());

            ProductoData productoData = new ProductoData();
            Producto producto = productoData.buscarProducto(idProducto);
            
            if (producto != null) {
                idProducto = producto.getIdProducto();
                producto = new Producto(idProducto, codigo, nombre, precio, stock, producto.isEstadoProducto());
                productoData.modificarProducto(producto);
            }
            borrarFilas();
            cargarTabla();
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero entero");
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Debe completar los campos");
        }
    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
      borrarDatos();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jtxtBuscarIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBuscarIdMouseClicked
        borrarDatos();
        borrarFilas();
        cargarTabla();
    }//GEN-LAST:event_jtxtBuscarIdMouseClicked

    private void jtblProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblProductosMousePressed
        borrarDatos();
        if (jtblProductos.getSelectedRow() > -1) {
            String idString = jtblProductos.getValueAt(jtblProductos.getSelectedRow(), 0).toString();
            int idProducto = Integer.parseInt(idString);        
        
            Producto producto = new Producto();
            ProductoData productoData = new ProductoData();
            
            producto = productoData.buscarProducto(idProducto);
            if (producto != null) {
                jtxtId.setText(String.valueOf(producto.getIdProducto()));
                jtxtCodigo.setText(String.valueOf(producto.getCodigoProducto()));
                jtxtNombre.setText(String.valueOf(producto.getNombreProducto()));
                jtxtPrecio.setText(Double.toString(producto.getPrecio()));
                jtxtStock.setText(Integer.toString(producto.getStock()));
                
                if(producto.isEstadoProducto() == true){
                    jbtnEliminar.setText("Eliminar");
                }else{
                    jbtnEliminar.setText("Restaurar");
                }
            }
        }
    }//GEN-LAST:event_jtblProductosMousePressed

    private void jtxtBuscarCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBuscarCodigoMouseClicked
        borrarDatos();
        borrarFilas();
        cargarTabla();
    }//GEN-LAST:event_jtxtBuscarCodigoMouseClicked

    private void jbtnBuscarPorCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarPorCodigoActionPerformed
        try{
            Producto producto = new Producto();
            ProductoData productoData = new ProductoData();
            
            producto = productoData.buscarProductoPorCodigo(jtxtBuscarCodigo.getText());
            if (producto != null) {
                jtxtId.setText(String.valueOf(producto.getIdProducto()));
                jtxtCodigo.setText(String.valueOf(producto.getCodigoProducto()));
                jtxtNombre.setText(String.valueOf(producto.getNombreProducto()));
                jtxtPrecio.setText(String.valueOf(producto.getPrecio()));
                jtxtStock.setText(String.valueOf(producto.getStock()));

            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe ingresar un Código");
        }
    }//GEN-LAST:event_jbtnBuscarPorCodigoActionPerformed

    private void jtxtIdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtxtIdCaretUpdate
        // TODO add your handling code here:
        if (!"".equals(jtxtId.getText())){
            jbtnGuardar.setEnabled(false);
            jbtnModificar.setEnabled(true);
        }
        else{
            jbtnGuardar.setEnabled(true);
            jbtnModificar.setEnabled(false);
        }
        System.out.println("El campo cambio de valor3"+ jtxtId.getText());
    }//GEN-LAST:event_jtxtIdCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBuscarId;
    private javax.swing.JButton jbtnBuscarPorCodigo;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JTable jtblProductos;
    private javax.swing.JTextField jtxtBuscarCodigo;
    private javax.swing.JTextField jtxtBuscarId;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtId;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPrecio;
    private javax.swing.JTextField jtxtStock;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        modelo.addColumn("ID");
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        modelo.addColumn("Estado");
        jtblProductos.setModel(modelo);
    }

    private void borrarFilas() {
        int f = jtblProductos.getRowCount() - 1; 
        for (; f >= 0; f--) { 
            modelo.removeRow(f);
        }
    }
    
    private void cargarTabla(){
        String act = "";
        
        for (Producto producto : producto.listarProductos()) {
            if (producto.isEstadoProducto()) {
                act = "Activo";
            } else {
                act = "Eliminado";
            }
            modelo.addRow(new Object[]{producto.getIdProducto(), producto.getCodigoProducto(), producto.getNombreProducto(), producto.getPrecio(), producto.getStock(), act});
        }
    }
    
    class CustomHeaderRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            // Cambiar el color de fondo de la cabecera de columna
            c.setBackground(new java.awt.Color(255,205,110)); // Cambia este color según tus preferencias

            return c;
        }
    }
    
     private void borrarDatos(){
        //borrar los datos
        jtxtBuscarId.setText("");
        jtxtBuscarCodigo.setText("");
        jtxtId.setText("");
        jtxtCodigo.setText("");
        jtxtNombre.setText("");
        jtxtPrecio.setText("");
        jtxtStock.setText("");
    }
}


